#modificamos el puerto por el cual se ejecuta nuestra aplicación
server.port=8090

#Configuraciones para base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi-market
#En la linea anterior, platzi-market es el nombre de la base de datos que estamos usando para esta aplicación
spring.datasource.username=postgres
spring.datasource.password=usuariopostgres