#indicamos el entorno en el que queremos trabajar, en este caso es dev:
spring.profiles.active=dev
#modificamos el context path de esta aplicación, este atributo será compartido para los perfiles dev (desarrollo) y pdn (producción)
server.servlet.context-path=/market/api
#En la linea anterior, el path /market/api es en donde vamos acceder a la api de nuestra aplicación